### ISSUE TITLE
SwaySwap MVP

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/swayswap#1]
- [x] fuel-core: release fuel-core with coin selection API (v0.3.2) @Voxelot (https://github.com/FuelLabs/fuel-core/pull/178)
- [x] fuel-core: run on the cloud @Voxelot
- [x] fuel-core: SSL cert/ports @Voxelot
- [x] fuel-core: mark coins as spent when tx runs @Voxelot
- [x] fuels-ts: integrate with the coin selection API (check with JC) @luizstacio
- [x] #20
- [x] fuels-ts: generate secret key, sign txs @luizstacio
- [x] frontend: very simple web wallet using the above TS SDK @luizstacio (https://github.com/FuelLabs/swayswap-demo/pull/6)
- [x] frontend: faucet: zero-input-one-output tx that gives user some coins @luizstacio
- [x] #17
- [x] frontend: github pages integration @luizstacio @adlerjohn #16 
- [x] frontend: drop-down @eureka-cpu (#8)
- [x] language: make `Result` work @sezna @emilyaherbert
    - [x] https://github.com/FuelLabs/sway/issues/814#issuecomment-1043455147 (nice to have)
    - [x] https://github.com/FuelLabs/sway/issues/308
    - [x] implement if lets (https://github.com/FuelLabs/sway/pull/815)
    - [x] add `size_of` that hooks in to the compiler and gets the size of the type in bytes (low prio) (https://github.com/FuelLabs/sway/pull/818)
    - [x] json abi needs structs that are logged (low prio)
- [x] stdlib: `Result` `unwrap()` function @adlerjohn (https://github.com/FuelLabs/sway-lib-std/pull/90)

**Comment by SilentCicero** [comment]
@Voxelot is this up to date, is there anything blocking SwaySwap from the client team currently?
